Repository rerun-io/kittest, pull requests merged in 2024-12, with the labels that each got.

#5 Add RELEASES.md and cargo machate CI
  .github/workflows/cargo_machete.yml
  RELEASES.md
  scripts/generate_changelog.py
  scripts/template_update.py
Labels: exclude from changelog

#6 Fix machete workflow
  .github/workflows/cargo_machete.yml
Labels: exclude from changelog, CI

#7 Add an example to README.md
  README.md
Labels: documentation, exclude from changelog
