Repository rerun-io/kittest, pull requests merged in 2025-08, with the labels that each got.

#14 Update to Rust 2024 edition, bump MSRV to 1.85
  .github/workflows/rust.yml
  Cargo.toml
  clippy.toml
  examples/basic_integration.rs
  examples/querying.rs
  rust-toolchain
  scripts/clippy_wasm/clippy.toml
  src/node.rs
Labels: include in changelog

#15 Update accesskit to 0.21, accesskit_consumer to 0.30
  Cargo.lock
  Cargo.toml
Labels: include in changelog, dependencies

#16 Make `By` clonable
  src/filter.rs
  src/query.rs
Labels: enhancement, include in changelog
